apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clienteapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clienteapi
    spec:
      containers:
      - name: clienteapi
        image: registry.ng.bluemix.net/pruebacontenedorespbarrien/clienteapi2:1
---
apiVersion: v1
kind: Service
metadata:
  name: clienteapi
  namespace: default
spec:
  ports:
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: clienteapi
  sessionAffinity: None
  type: LoadBalancer

